name: Build Java with secrets

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
        (github.event_name == 'pull_request' && 
         github.event.pull_request.base.ref == 'main' && github.head_ref == 'test')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test
        env:
          MY_SECRET_KEY: ${{ secrets.SECRET_NAME }}
